import Foundation

struct CDNProduct: Identifiable, Equatable, Sendable {
    var id: String { code }
    let name: String
    let code: String
    var regions: [String] = []
    var isLoading = false
    var loadFailed = false

    static func == (lhs: CDNProduct, rhs: CDNProduct) -> Bool {
        lhs.name == rhs.name && lhs.code == rhs.code && lhs.regions == rhs.regions && lhs.isLoading == rhs.isLoading && lhs.loadFailed == rhs.loadFailed
    }

    static let builtInList: [CDNProduct] = [
        // Platform
        CDNProduct(name: "Battle.net Agent", code: "agent"),
        CDNProduct(name: "Battle.net Agent Beta", code: "agent_beta"),
        CDNProduct(name: "Battle.net Launcher", code: "bna"),
        CDNProduct(name: "Bootstrapper", code: "bts"),
        CDNProduct(name: "Client", code: "clnt"),
        CDNProduct(name: "Game Catalog", code: "catalogs"),
        // Blizzard Arcade Collection
        CDNProduct(name: "Blizzard Arcade Collection", code: "rtro"),
        CDNProduct(name: "Blizzard Arcade Collection Development Region", code: "rtrodev"),
        // Diablo
        CDNProduct(name: "Diablo 3 Beta (2013)", code: "d3b"),
        CDNProduct(name: "Diablo I", code: "drtl"),
        CDNProduct(name: "Diablo I Unknown 2", code: "drtl2"),
        CDNProduct(name: "Diablo II: Resurrected", code: "osi"),
        CDNProduct(name: "Diablo II: Resurrected Beta", code: "osib"),
        CDNProduct(name: "Diablo II: Resurrected Development Region", code: "osidev"),
        CDNProduct(name: "Diablo II: Resurrected Early Review", code: "osia"),
        CDNProduct(name: "Diablo II: Resurrected Public Test Realm", code: "osit"),
        CDNProduct(name: "Diablo III", code: "d3"),
        CDNProduct(name: "Diablo III China", code: "d3cn"),
        CDNProduct(name: "Diablo III Public Test Realm", code: "d3t"),
        CDNProduct(name: "Diablo Immortal", code: "anbs"),
        CDNProduct(name: "Diablo Immortal", code: "anbs-event"),
        CDNProduct(name: "Diablo Immortal (Dev) - BM", code: "anbs-retail-dev-1"),
        CDNProduct(name: "Diablo Immortal Development Region", code: "anbsdev"),
        CDNProduct(name: "Diablo Immortal PTR", code: "anbs-ptr"),
        CDNProduct(name: "Diablo Immortal PTR (Dev)", code: "anbs-ptr-dev-1"),
        CDNProduct(name: "Diablo Immortal PTR (RC)", code: "anbs-ptr-rc"),
        CDNProduct(name: "Diablo IV", code: "fenris"),
        CDNProduct(name: "Diablo IV - Server Slam", code: "fenrisb"),
        CDNProduct(name: "Diablo IV - Tech Alpha", code: "fenrisdev"),
        CDNProduct(name: "Diablo IV Diablo_Play 1", code: "fenrise"),
        CDNProduct(name: "Diablo IV Diablo_Play 2", code: "fenrise2"),
        CDNProduct(name: "Diablo IV Public Test Realm", code: "fenristest"),
        // GDT
        CDNProduct(name: "GDT", code: "gdt"),
        CDNProduct(name: "GDT Dev 1", code: "gdt-retail-dev-1"),
        CDNProduct(name: "GDT Dev 2", code: "gdt-retail-dev-2"),
        CDNProduct(name: "GDT RC", code: "gdt-retail-rc"),
        // Hearthstone
        CDNProduct(name: "Hearthstone", code: "hsb"),
        CDNProduct(name: "Hearthstone", code: "hsrc"),
        CDNProduct(name: "Hearthstone Alpha", code: "hsdev"),
        CDNProduct(name: "Hearthstone Beta", code: "hsbt"),
        CDNProduct(name: "Hearthstone Event Realm", code: "hse"),
        CDNProduct(name: "Hearthstone Event Realm 1", code: "hse1"),
        CDNProduct(name: "Hearthstone Tournament Realm", code: "hsc"),
        // Heroes of the Storm
        CDNProduct(name: "Heroes of the Storm", code: "hero"),
        CDNProduct(name: "Heroes of the Storm Public Test Realm", code: "herot"),
        CDNProduct(name: "Heroes of the Storm Tournament Realm", code: "heroc"),
        // Overwatch
        CDNProduct(name: "Overwatch", code: "pro"),
        CDNProduct(name: "Overwatch 2", code: "pro2"),
        CDNProduct(name: "Overwatch 2 Overwatch World Cup 2019", code: "proms"),
        CDNProduct(name: "Overwatch 2 Preview", code: "prodemo4"),
        CDNProduct(name: "Overwatch 2 Preview 2", code: "prodemo5"),
        CDNProduct(name: "Overwatch 2 Vendor", code: "prov"),
        CDNProduct(name: "Overwatch 2 Vendor AC", code: "provac"),
        CDNProduct(name: "Overwatch 2 Vendor BVID", code: "provbv"),
        CDNProduct(name: "Overwatch 2 Vendor Competitive", code: "prodemo3"),
        CDNProduct(name: "Overwatch Beta", code: "prob"),
        CDNProduct(name: "Overwatch CN Vidcap 1", code: "providcn1"),
        CDNProduct(name: "Overwatch CN Vidcap 2", code: "providcn2"),
        CDNProduct(name: "Overwatch CN Vidcap 3", code: "providcn3"),
        CDNProduct(name: "Overwatch Dev Five", code: "proindev"),
        CDNProduct(name: "Overwatch Dev Four", code: "prodemo2"),
        CDNProduct(name: "Overwatch Dev One", code: "prodev"),
        CDNProduct(name: "Overwatch Dev Ops 1", code: "prodevops"),
        CDNProduct(name: "Overwatch Dev Ops 2", code: "prodevops2"),
        CDNProduct(name: "Overwatch Dev Three", code: "prodemo"),
        CDNProduct(name: "Overwatch Dev Two", code: "proc3"),
        CDNProduct(name: "Overwatch Esports", code: "proc5"),
        CDNProduct(name: "Overwatch Esports", code: "proev"),
        CDNProduct(name: "Overwatch League Viewer", code: "procr"),
        CDNProduct(name: "Overwatch League Viewer", code: "procr2"),
        CDNProduct(name: "Overwatch Public Test Region", code: "prot"),
        CDNProduct(name: "Overwatch Tournament A", code: "proc"),
        CDNProduct(name: "Overwatch Tournament Asia", code: "proc_kr"),
        CDNProduct(name: "Overwatch Tournament B", code: "proc2"),
        CDNProduct(name: "Overwatch Tournament B Asia", code: "proc2_kr"),
        CDNProduct(name: "Overwatch Tournament B China", code: "proc2_cn"),
        CDNProduct(name: "Overwatch Tournament B Europe", code: "proc2_eu"),
        CDNProduct(name: "Overwatch Tournament C", code: "proc4"),
        CDNProduct(name: "Overwatch Tournament China", code: "proc_cn"),
        CDNProduct(name: "Overwatch Tournament Europe", code: "proc_eu"),
        CDNProduct(name: "Overwatch User Test Realm", code: "proutr"),
        CDNProduct(name: "Overwatch Vendor Competitive", code: "provcomp"),
        // StarCraft
        CDNProduct(name: "StarCraft", code: "s1"),
        CDNProduct(name: "StarCraft II", code: "s2"),
        CDNProduct(name: "StarCraft II China", code: "s2c"),
        CDNProduct(name: "StarCraft II Public Test Realm", code: "s2t"),
        CDNProduct(name: "StarCraft Public Test Realm", code: "s1t"),
        // Warcraft
        CDNProduct(name: "Warcraft I: Remastered", code: "w1r"),
        CDNProduct(name: "WarCraft II: Battle.net Edition", code: "w2bn"),
        CDNProduct(name: "Warcraft II: Remastered", code: "w2r"),
        CDNProduct(name: "Warcraft II: Remastered Internal Alpha", code: "w2rd"),
        CDNProduct(name: "Warcraft III", code: "w3"),
        CDNProduct(name: "Warcraft III - Legacy TFT 1.29", code: "w3-legacy-tft"),
        CDNProduct(name: "Warcraft III Public Test Realm", code: "w3t"),
        CDNProduct(name: "Warcraft III Public Test Realm (Internal)", code: "w3d"),
        CDNProduct(name: "Warcraft III: Reforged Beta", code: "w3b"),
        CDNProduct(name: "Warcraft Rumble", code: "gryphon"),
        CDNProduct(name: "Warcraft Rumble Submission", code: "gryphonv"),
        CDNProduct(name: "Warcraft Rumble Tech Test Development Region", code: "gryphondev"),
        // World of Warcraft
        CDNProduct(name: "World of Warcraft", code: "wow"),
        CDNProduct(name: "World of Warcraft Burning Crusade Anniversary", code: "wow_anniversary"),
        CDNProduct(name: "World of Warcraft Classic", code: "wow_classic_era"),
        CDNProduct(name: "World of Warcraft Dark Realm (Deprecated)", code: "wowlivetest"),
        CDNProduct(name: "World of Warcraft Dark Realm Test", code: "wowlivetest2"),
        CDNProduct(name: "World of Warcraft Event 3", code: "wowe3"),
        CDNProduct(name: "World of Warcraft Event Realm", code: "wowe1"),
        CDNProduct(name: "World of Warcraft Mainline Internal Test Development Region", code: "wowdev"),
        CDNProduct(name: "World of Warcraft Midnight Beta", code: "wow_beta"),
        CDNProduct(name: "World of Warcraft Mists of Pandaria Classic", code: "wow_classic"),
        CDNProduct(name: "World of Warcraft MOP Classic Beta", code: "wow_classic_beta"),
        CDNProduct(name: "World of Warcraft PTR", code: "wow_classic_era_ptr"),
        CDNProduct(name: "World of Warcraft PTR", code: "wowt"),
        CDNProduct(name: "World of Warcraft PTR", code: "wowxptr"),
        CDNProduct(name: "World of Warcraft Submissions", code: "wowz"),
        CDNProduct(name: "World of Warcraft Titan Reforged Classic", code: "wow_classic_titan"),
        CDNProduct(name: "World of Warcraft Vendor 1", code: "wowv"),
        CDNProduct(name: "World of Warcraft Wrath of the Lich King Classic PTR", code: "wow_classic_ptr"),
        // Call of Duty
        CDNProduct(name: "Call of Duty", code: "auks"),
        CDNProduct(name: "Call of Duty Cortez RC", code: "auksrc"),
        CDNProduct(name: "Call of Duty Cortez RC 2", code: "auksrc2"),
        CDNProduct(name: "Call of Duty Dev", code: "auksdev"),
        CDNProduct(name: "Call of Duty eSports Player", code: "auksesp"),
        CDNProduct(name: "Call of Duty eSports Staff", code: "auksess"),
        CDNProduct(name: "Call of Duty Event 2", code: "aukse2"),
        CDNProduct(name: "Call of Duty: Black Ops 4", code: "viper"),
        CDNProduct(name: "Call of Duty: Black Ops 4 Alpha", code: "viperdev"),
        CDNProduct(name: "Call of Duty: Black Ops Cold War", code: "zeus"),
        CDNProduct(name: "Call of Duty: Black Ops Cold War Beta", code: "zeusb"),
        CDNProduct(name: "Call of Duty: Black Ops Cold War Black Ops Cold War", code: "zeusr"),
        CDNProduct(name: "Call of Duty: Black Ops Cold War CDL Event", code: "zeuscdlevent"),
        CDNProduct(name: "Call of Duty: Black Ops Cold War CDL Player", code: "zeusc"),
        CDNProduct(name: "Call of Duty: Black Ops Cold War CDL Staff", code: "zeuscdlstaff"),
        CDNProduct(name: "Call of Duty: Black Ops Cold War Closed Internal Alpha", code: "zeusa"),
        CDNProduct(name: "Call of Duty: Black Ops Cold War Development Region", code: "zeusdev"),
        CDNProduct(name: "Call of Duty: Black Ops Cold War Event 1", code: "zeusevent"),
        CDNProduct(name: "Call of Duty: Modern Warfare", code: "odin"),
        CDNProduct(name: "Call of Duty: Modern Warfare II", code: "nina"),
        CDNProduct(name: "Call of Duty: Modern Warfare II Alpha", code: "auksa"),
        CDNProduct(name: "Call of Duty: Modern Warfare II Beta", code: "auksb"),
        CDNProduct(name: "Call of Duty: Modern Warfare II E-Sports Event", code: "auksese"),
        CDNProduct(name: "Call of Duty: Modern Warfare II Event 1", code: "aukse"),
        CDNProduct(name: "Call of Duty: Modern Warfare III", code: "pinta"),
        CDNProduct(name: "Call of Duty: Modern Warfare Modern Warfare Development Region", code: "odindev"),
        CDNProduct(name: "Call of Duty: MW2 Campaign Remastered", code: "lazr"),
        CDNProduct(name: "Call of Duty: Vanguard", code: "fore"),
        CDNProduct(name: "Call of Duty: Vanguard Alpha", code: "forea"),
        CDNProduct(name: "Call of Duty: Vanguard Beta", code: "foreb"),
        CDNProduct(name: "Call of Duty: Vanguard CDL Player", code: "forec"),
        CDNProduct(name: "Call of Duty: Vanguard CDL Staff", code: "forecdlstaff"),
        CDNProduct(name: "Call of Duty: Vanguard Development Region", code: "foredev"),
        CDNProduct(name: "Call of Duty: Warzone Alpha", code: "odina"),
        CDNProduct(name: "Call of Duty: Warzone Beta", code: "odinb"),
        CDNProduct(name: "Call of Duty: Warzone Event 1", code: "odine"),
        // Sea of Thieves
        CDNProduct(name: "Sea of Thieves", code: "scor"),
        CDNProduct(name: "Sea of Thieves Beta Dev 1", code: "scor-beta-dev-1"),
        CDNProduct(name: "Sea of Thieves Insiders", code: "scor-beta"),
        CDNProduct(name: "Sea of Thieves Retail Dev 1", code: "scor-retail-dev-1"),
        CDNProduct(name: "Sea of Thieves Retail RC", code: "scor-retail-rc"),
        // Tony Hawk's
        CDNProduct(name: "Tony Hawk's™ Pro Skater™ 3 + 4", code: "lbra"),
        CDNProduct(name: "Tony Hawk's™ Pro Skater™ 3 + 4 Developer 1", code: "lbra-retail-dev-1"),
        CDNProduct(name: "Tony Hawk's™ Pro Skater™ 3 + 4 Foundry Demo Developer-1", code: "lbra-demo-dev-1"),
        CDNProduct(name: "Tony Hawk's™ Pro Skater™ 3 + 4 Retail RC", code: "lbra-retail-rc"),
        CDNProduct(name: "Tony Hawk's™ Pro Skater™ 3 + 4 Tony Hawk's Pro Skater 3+4 - Demo RC", code: "lbra-demo-rc"),
        CDNProduct(name: "Tony Hawk's™ Pro Skater™ 3 + 4 – Demo", code: "lbra-demo"),
        // Crash Bandicoot
        CDNProduct(name: "Crash Bandicoot 4: It's About Time", code: "wlby"),
        CDNProduct(name: "Crash Bandicoot 4: It's About Time Crash Development Region", code: "wlbydev"),
        // Avowed
        CDNProduct(name: "Avowed", code: "aqua"),
        CDNProduct(name: "Avowed Artbook & Soundtrack", code: "aqua-artbook"),
        CDNProduct(name: "Avowed Artbook & Soundtrack RC", code: "aqua-artbook-rc"),
        CDNProduct(name: "Avowed Developer 1", code: "aqua-retail-dev-1"),
        CDNProduct(name: "Avowed Developer 2", code: "aqua-artbook-dev-1"),
        CDNProduct(name: "Avowed RC", code: "aqua-retail-rc"),
        // Doom: The Dark Ages
        CDNProduct(name: "Doom: The Dark Ages", code: "aris"),
        CDNProduct(name: "Doom: The Dark Ages Aries RC", code: "aris-retail-rc"),
        CDNProduct(name: "Doom: The Dark Ages Artbook Dev", code: "aris-artbook-dev-1"),
        CDNProduct(name: "Doom: The Dark Ages Artbook RC", code: "aris-artbook-rc"),
        CDNProduct(name: "Doom: The Dark Ages Developer 1", code: "aris-retail-dev-1"),
        CDNProduct(name: "Doom: The Dark Ages DOOM: The Dark Ages Digital Artbook and Original Soundtrack", code: "aris-artbook"),
        // The Outer Worlds 2
        CDNProduct(name: "The Outer Worlds 2", code: "ark"),
        CDNProduct(name: "The Outer Worlds 2 Artbook", code: "ark-artbook"),
        CDNProduct(name: "The Outer Worlds 2 TOW2 Artbook Dev", code: "ark-artbook-dev-1"),
        CDNProduct(name: "The Outer Worlds 2 TOW2 Artbook RC", code: "ark-artbook-rc"),
        CDNProduct(name: "The Outer Worlds 2 TOW2 Dev", code: "ark-retail-dev-1"),
        CDNProduct(name: "The Outer Worlds 2 TOW2 RC", code: "ark-retail-rc"),
    ]
}
